<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<form name="frmImageResize" action="" method="post" enctype="multipart/form-data">
  <input type="file" name="myImage" /> 
  <input type="submit" name="submit" value="Submit" />
</form>
</body>
</html>